### ISSUE TITLE
Cannot get to work

### ISSUE THREAD

**Issue by jrote1** [recallfx/node-red-contrib-eufy-security#1]
I am trying to get this to work in nodered but I am having a few issues. I've added the node to the flow and add eufy-config but my username/password do not seem to get saved. Everytime I check the config they are empty. Also when I deploy the flow I get the following error 

```
Flows stopped due to missing node types.

eufy-config
eufy-security
```

Any help would be greatly appreciated, if I can provide anymore information then please let me know

**Comment by recallfx** [comment]
Regarding credentials, I had similar issue, where I solved by going to `settings.json` and uncomment `credentialSecret` (change the key).

Regarding other issue, can you paste the output of `npx node-red`?
