### ISSUE TITLE
Disconnect after a couple of minutes

### ISSUE THREAD

**Issue by nitram-rem** [recallfx/node-red-contrib-eufy-security#11]
Hi,

i run the eufy-security in iobroker and when i change and deploy the node the node will become connected but after a couple minutes the nodes disconnects:
![Screenshot 2021-12-11 090528](https://user-images.githubusercontent.com/62590957/145669392-802b8ce6-68df-4c51-955c-7a0bfd15174a.png)

I can't find any possibility to enter such a token. What is also strange from time i will be asked to enter a captcha.

**Comment by nitram-rem** [comment]
Or can you please describe how an invite can be used with a new account? Then I will create one especially for this module. As far as expect a mail configuration is necessary. But I do not know how I can configure mail on iobroker or node-red to receive the invite. Are there other configurations necessary?

**Comment by nitram-rem** [comment]
I it is now working, why ever, i cant find anything which i changed. So you can close this issue. But it would be nice if you can explain how invites can be used to use an dedicated account for the module.

**Comment by MJJH** [comment]
Going further on this issue. I have the same problem, I have tried 5 fresh accounts so far and all end up with this exact output. 

Anybody that can help me with this?
