### ISSUE TITLE
Connection and configuration problems

### ISSUE THREAD

**Issue by boomvalt** [recallfx/node-red-contrib-eufy-security#16]
I'm having problems connecting to eufy security. It seems to be related to repeated emails with a one-time authentication codes I keep getting.
Configuration is a problem too as the only device I have is the 2k pan-tilt camera. I can put in the Cam SN, but what should I do with the Station SN as I have no station? Leave it blank?

**Comment by recallfx** [comment]
You would need to use `connect` command with login options like this:

```
{
    "command": "connect",
    "loginOptions": {
        "verifyCode": "123"
    }
}
```
