### ISSUE TITLE
Unable to command enable/disable camera

### ISSUE THREAD

**Issue by hakarune** [recallfx/node-red-contrib-eufy-security#17]
I've installed this and set up a basic inject and debug output flow to try and to send commands to disable and enable camera but it never works. How do you actually send commands to the camera to control it (disable/enable, change modes, indicator light on or off etc)? I can't get any command to work, can anyone show a set up example flow with how the command is supposed to sent via node red? How is the inject node supposed to be formatted to control stuff?

**Comment by recallfx** [comment]
There are two [examples](https://github.com/recallfx/node-red-contrib-eufy-security/tree/master/examples) how to use this node, you can import each file and try playing around.
