### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by bmshine** [recallfx/node-red-contrib-eufy-security#18]
The node always shows connecting. If i start the node i get the following: 
25.11.2022, 23:15:35
msg : string[14]
"Generic Error:"
25.11.2022, 23:15:36
msg : string[11]
"Token error"
Is there a way to fix it?
BR Markus

**Comment by markcudok** [comment]
Hi Markus, I got the same error, looks like this problem started when I upgraded Node-RED to 13.5.3.

**Comment by jageerdarjaggy** [comment]
I still have this problem. strangely enough, it suddenly started to work and continued to develop my flow. and then suddenly it stopped , no change to node-red or anything, but just stopped and started getting "token error" what can i do?

**Comment by jageerdarjaggy** [comment]
something to do with tokens when logging in.... not sure why it suddenly started to work and then stopped again after couple of hours... any help ?

**Comment by bmshine** [comment]
Maybe it will work if the libraries (eufy-security-client) are updated to the newest version (2.3.0)
Right now an very old version is used. I have tried to replace it, but it doesn't looks compatible. :(

**Comment by jageerdarjaggy** [comment]
I have also installed the latest version of eufy-client libraries,but no
change

**Comment by itb3** [comment]
same issue here. stopped working with "generic error: token error", started working again at some point after restarting flows etc (do not know when exactly, tried a lot), but stopped working again after a few hours. now several days of consistent "token error". restarting flows, node-red or machine does not help.

**Comment by jageerdarjaggy** [comment]
I think the original developer is no longer maintaining it. This was a good
solution but as with most opensource contrib solutions, things get abandoned

**Comment by Sprocket02** [comment]
That's too bad. Does anyone have this running for them now? Looking for a solution for OpenHAB.

**Comment by jageerdarjaggy** [comment]
Nope, no integration for now

**Comment by robertusw** [comment]
Same problem here. No solution???

I use my Eyeful Security alarm system to trigger behavior of my entire Home Automation (Tado, Sonos, Hue, ....). The status of the alarm (Off, Home, Away, Long Away) switches my smart devices through NodeRed. Because the Eufy Security integration no longer works my smart home system is also broken (sort of). Looked to switch over to Homey Pro but read there same problems with (official) apps made by Atom that are updated (for example Tado) and lost important functionality.

Let's hope that somebody makes a new integration?!

**Comment by jageerdarjaggy** [comment]
Utterly disappointing...

**Comment by Leethal1977** [comment]
Hi - has anyone managed to get this working.  Not overly experienced with node-red - managed to get it running in a Docker container, installed the eufy-security-client (not sure what else I need to do after installing?) but just get the "error", "generic error" or "token error" responses in the node-reg logs.  Have been trying to get this working for a couple of days now and discovered this thread - any pointers would be very much appreciated!

**Comment by recallfx** [comment]
I have updated code with #21. In my case, the issue was with `captcha request` event, that was not handled, thus no messages. Now it will show directly on the node, if captcha/TFA or generic connection error happened.
