### ISSUE TITLE
Create push credentials Error 

### ISSUE THREAD

**Issue by mgreg89** [recallfx/node-red-contrib-eufy-security#2]
Hello,

first of all: Thank you very much for this contribution! We have been waiting for this since we have our first eufy device in our smart home :)

We could successfully test everything with is triggered by an inject node. However, events were not pushed to the node (like if someone rings at the door or when motion is detected) and we encounter the following error messages:

![image](https://user-images.githubusercontent.com/39031465/131258506-6cf60cb0-ae3e-469c-be7a-36f3273b7570.png)

These get printed out several times on startup. 

Is this behaviour already known? Are we doing something wrong?

Thank you very much in advance!

**Comment by recallfx** [comment]
Hello, I have not encountered this issue, does push notifications work for you on original Eufy Security app?
Here is my startup:
![out](https://user-images.githubusercontent.com/3793207/131809825-beb89986-e960-465f-9baa-32cd6a482bf9.gif)

**Comment by mgreg89** [comment]
Hello @recallfx 
Yes, push notifications work pretty normal in the Eufy app. I tried the same startup as you, but the errors occure every time. I have no clue what's going wrong here.

**Comment by mgreg89** [comment]
Resolved by updating to the latest npm version. Issue was caused by failing preflight request of subdependency axios.
