### ISSUE TITLE
dependency issue on installation

### ISSUE THREAD

**Issue by Richtation** [recallfx/node-red-contrib-eufy-security#26]
Hi Team,

I would love to use this package but have a hard time to install.
I tried within RaspberryMatic with NodeRED v1.2.9 but get this error:

> 2023-12-30T14:14:49.230Z installieren : node-red-contrib-eufy-security 0.1.1
> 2023-12-30T14:14:49.461Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-eufy-security@0.1.1
> 2023-12-30T14:14:59.697Z [err] npm
> 2023-12-30T14:14:59.697Z [err]  WARN EBADENGINE Unsupported engine {
> 2023-12-30T14:14:59.697Z [err] npm WARN EBADENGINE   package: 'node-red-contrib-eufy-security@0.1.1',
> 2023-12-30T14:14:59.697Z [err] npm WARN 
> 2023-12-30T14:14:59.698Z [err] EBADENGINE   required: { node: '>=16.0.0' },
> 2023-12-30T14:14:59.698Z [err] npm WARN EBADENGINE
> 2023-12-30T14:14:59.698Z [err]    current: { node: 'v14.16.0', npm: '7.6.3' }
> 2023-12-30T14:14:59.698Z [err] npm WARN EBADENGINE }
> 2023-12-30T14:14:59.701Z [err] npm WARN
> 2023-12-30T14:14:59.701Z [err]  EBADENGINE Unsupported engine {
> 2023-12-30T14:14:59.701Z [err] npm WARN EBADENGINE   package: '@cospired/i18n-iso-languages@4.1.0',
> 2023-12-30T14:14:59.701Z [err] npm 
> 2023-12-30T14:14:59.702Z [err] WARN EBADENGINE   required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },
> 2023-12-30T14:14:59.702Z [err] npm WARN
> 2023-12-30T14:14:59.702Z [err]  EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
> 2023-12-30T14:14:59.702Z [err] npm WARN 
> 2023-12-30T14:14:59.702Z [err] EBADENGINE }
> 2023-12-30T14:14:59.706Z [err] npm WARN
> 2023-12-30T14:14:59.707Z [err]  EBADENGINE Unsupported engine {
> 2023-12-30T14:14:59.707Z [err] npm WARN EBADENGINE   package: 'eufy-security-client@2.9.1',
> 2023-12-30T14:14:59.707Z [err] npm WARN
> 2023-12-30T14:14:59.707Z [err]  EBADENGINE   required: { node: '>=18.0.0' },
> 2023-12-30T14:14:59.707Z [err] npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
> 2023-12-30T14:14:59.707Z [err] npm WARN EBADENGINE }
> 2023-12-30T14:14:59.710Z [err] npm WARN 
> 2023-12-30T14:14:59.710Z [err] EBADENGINE Unsupported engine {
> 2023-12-30T14:14:59.710Z [err] npm WARN EBADENGINE   package: 'fast-unique-numbers@8.0.12',
> 2023-12-30T14:14:59.710Z [err] npm WARN 
> 2023-12-30T14:14:59.710Z [err] EBADENGINE   required: { node: '>=16.1.0' },
> 2023-12-30T14:14:59.710Z [err] npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
> 2023-12-30T14:14:59.710Z [err] npm 
> 2023-12-30T14:14:59.711Z [err] WARN EBADENGINE }
> 2023-12-30T14:14:59.718Z [err] npm WARN EBADENGINE Unsupported engine {
> 2023-12-30T14:14:59.718Z [err] npm WARN EBADENGINE   package: 'mqtt@5.3.4',
> 2023-12-30T14:14:59.718Z [err] npm WARN EBADENGINE   required: { node: '>=16.0.0' },
> 2023-12-30T14:14:59.718Z [err] npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
> 2023-12-30T14:14:59.718Z [err] npm WARN EBADENGINE }
> 2023-12-30T14:14:59.719Z [err] npm WARN
> 2023-12-30T14:14:59.719Z [err]  EBADENGINE Unsupported engine {
> 2023-12-30T14:14:59.719Z [err] npm WARN EBADENGINE   package: 'readable-stream@4.5.2',
> 2023-12-30T14:14:59.720Z [err] npm WARN EBADENGINE   required: { node: '^12.22.0 || ^14.17.0 || >=16.0.0' },
> 2023-12-30T14:14:59.720Z [err] npm WARN 
> 2023-12-30T14:14:59.720Z [err] EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
> 2023-12-30T14:14:59.720Z [err] npm 
> 2023-12-30T14:14:59.720Z [err] WARN EBADENGINE }

So it seems, that node >=18.x needed to be installed. As it's running on a Raspberry3 this does not seem to be possible by now.

So I thought giving it a try via Docker on a recent MacBook Pro like described here: https://nodered.org/docs/getting-started/docker#dockerfile-which-copies-in-local-resources

This installed NodeRED v3.1.3 but if I try to install I still get a package that needs a higher version…

> 2023-12-30T14:18:07.735Z Installieren : node-red-contrib-eufy-security 0.1.1
> 
> 2023-12-30T14:18:07.758Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-eufy-security@0.1.1
> 2023-12-30T14:18:07.988Z [err] npm
> 2023-12-30T14:18:07.989Z [err]  WARN config production Use `--omit=dev` instead.
> 2023-12-30T14:18:17.059Z [err] npm ERR! code EBADENGINE
> 2023-12-30T14:18:17.061Z [err] npm ERR! engine Unsupported engine
> 2023-12-30T14:18:17.061Z [err] npm ERR! engine Not compatible with your version of node/npm: eufy-security-client@2.9.1
> 2023-12-30T14:18:17.061Z [err] npm ERR! 
> 2023-12-30T14:18:17.061Z [err] notsup Not compatible with your version of node/npm: eufy-security-client@2.9.1
> 2023-12-30T14:18:17.061Z [err] npm ERR! notsup Required: {"node":">=18.0.0"}
> 2023-12-30T14:18:17.061Z [err] npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}

So what version of NodeRED does this package require in order to work? Or is it possible to adjust the dependencies to a more "convenient" version level to be more compatible with useable standard versions?

Thanks for your thoughts.

**Comment by b14ckw1d0w** [comment]
It doesn't require any version of NodeRED to function since it doesn't function at all. There is no way of entering the 2fa code or captcha code and there is no sign of any devs around so I guess this is another dead project.

**Comment by Richtation** [comment]
> It doesn't require any version of NodeRED to function since it doesn't function at all. There is no way of entering the 2fa code or captcha code and there is no sign of any devs around so I guess this is another dead project.

Thanks for the comment. I was able to get this to work - for the docker-version of node-red you can define what version of node and npm should be used:
https://github.com/node-red/node-red-docker/blob/master/README.md

so I used `amd64/node:18-alpine` and got it to work. Sadly it still seems to not work on RaspberryMatic but that might be another topic. So closing for now…
