### ISSUE TITLE
Documentation eufy config / Events not relaiable

### ISSUE THREAD

**Issue by guny74** [recallfx/node-red-contrib-eufy-security#4]
Hello,

Is there a documenation  of the eufy config parameters ? 
Sometimes motion detection are delivered from the node, but after the first event it seam to stop working....

Maybe wrong config e.g. polling  intervall or so ?

Regards

**Comment by guny74** [comment]
Any help or idea what wrong ?

**Comment by guny74** [comment]
After using a freh new "guest" account ist works...I did it the same ways many times ..and suddenly it works

**Comment by recallfx** [comment]
It is alive:D
