### ISSUE TITLE
how to set guard mode and how to use other not listed commands?

### ISSUE THREAD

**Issue by guny74** [recallfx/node-red-contrib-eufy-security#6]
Hello, 

there are some very interesting/useful commands which seams not to be supported.

I this project to be continued / exnhanced ?

**Comment by recallfx** [comment]
Hello,
This project is based on https://github.com/bropat/eufy-security-client. What commands are not supported?

**Comment by recallfx** [comment]
Oh, you mean `guard mode`? Should not be very hard to add.

**Comment by guny74** [comment]
> Hello, This project is based on https://github.com/bropat/eufy-security-client. What commands are not supported?

I know, but did not found a realc command list and not the "transfer" to the WS how to use this not "listed/found" command

**Comment by MJJH** [comment]
How about the features that they have listed under 'devices' like "Start livestream (local/remote p2p or rtmp over cloud)" and "Stop livestream (local/remote p2p or rtmp over cloud)"?

**Comment by nitram-rem** [comment]
HI did you had a chance to add a command to change the guard mode?
