### ISSUE TITLE
Example for Eufy Alarm

### ISSUE THREAD

**Issue by nitram-rem** [recallfx/node-red-contrib-eufy-security#7]
Hi,

i'm currently trying to create a node-red flow which receives an alarm and start a flow in Homee to switch all light on. The question is how can i analyse the incoming alarm event in a node-red function to create at the end the correct payload to sned it to the Homee. Would it be possible to provide some function examples?

greetings

**Comment by recallfx** [comment]
Hello,
Here is an example of basic motion flow: https://github.com/recallfx/node-red-contrib-eufy-security/blob/master/examples/motion.json

Should look like this: 
![image](https://user-images.githubusercontent.com/3793207/140062184-7b6359f8-c480-4a91-a383-3d102583aa04.png)

Here `motion` and `alarm` are simple debug nodes, that can be replaced with anything, for example switch on hubitat lights:
![image](https://user-images.githubusercontent.com/3793207/140063864-b337ae52-c9e6-45f5-a8b5-cbec4796385c.png)

Debug node `motion` will print lots of information like this:
![image](https://user-images.githubusercontent.com/3793207/140064057-c6203d3c-c891-4cfc-b0ce-6bbb5ecf2681.png)

Most important is to setup `eufy-security` node to subscribe on these events (plus alarm event that is at the top)
![image](https://user-images.githubusercontent.com/3793207/140062651-96ee310d-f605-4594-9bd1-18d5be6e8cde.png)

**Comment by nitram-rem** [comment]
Hi Marius,

thanks for your fast answer. Next question. Is it possible to cacade two switch nodes? On the first iw ill differ betwenn Alarm, Motion, Close and any other Event and on the cascaded i will differ in the motion tree between the different camera's so i can switch the light on in the correct region.

![gxIQbnbP7A](https://user-images.githubusercontent.com/62590957/140071393-c59815ee-5c1e-4481-af2a-3e1f6905aa19.png)

second switch:

![td6VjWkv86](https://user-images.githubusercontent.com/62590957/140071591-c4355cb9-481e-47a8-af3c-d3e9a59340f6.png)


greetings

Martin

**Comment by recallfx** [comment]
You can cascade, the result of the switch will be same message, then you can check based on that message properties what else to do. In my case `msg.payload.device.name` is `Kids room` and I can wire logic based on that.

**Comment by nitram-rem** [comment]
Hi, next question is it also possible to control the Eufy central using Node-red? As an example woult it be possible to switch between the securtiy modes? Like switch from at home to absend or geofencing? And if yes how should the command be formated?
