### ISSUE TITLE
Install in ioBroker with node-red

### ISSUE THREAD

**Issue by nitram-rem** [recallfx/node-red-contrib-eufy-security#9]
HI when i tra to install the module in a node-red running on an ioBroker i get the follwign messge:

node-red.0 | 2021-11-15 14:37:26.122 | warn | 15 Nov 13:37:26 - [warn] [node-red-contrib-eufy-security/eufy-security] SyntaxError: Unexpected token '.' (line:24) 15 Nov 13:37:26 - [warn] ------------------------------------------------------
-- | -- | -- | --

Do you have an idea?

**Comment by recallfx** [comment]
This is related to https://github.com/recallfx/node-red-contrib-eufy-security/issues/5 
Your ioBroker is running on node version older than v14.

**Comment by nitram-rem** [comment]
According to the Adapter readme it should be 1.17.2. I run the node-red adapter 2.4.1
